services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  MoveElevator\Typo3LoginWarning\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  # Interface binding for geolocation service
  MoveElevator\Typo3LoginWarning\Service\GeolocationServiceInterface:
    alias: MoveElevator\Typo3LoginWarning\Service\IpApiGeolocationService

  MoveElevator\Typo3LoginWarning\Notification\EmailNotification:
    public: true

  MoveElevator\Typo3LoginWarning\Detector\NewIpDetector:
    public: true

  MoveElevator\Typo3LoginWarning\Detector\LongTimeNoSeeDetector:
    public: true


  MoveElevator\Typo3LoginWarning\Security\LoginNotification:
    tags:
      - name: event.listener
        identifier: 'move-elevator/typo3-login-warning/login-notification'