services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  MoveElevator\Typo3LoginWarning\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  # Interface binding for geolocation service
  MoveElevator\Typo3LoginWarning\Service\GeolocationServiceInterface:
    alias: MoveElevator\Typo3LoginWarning\Service\IpApiGeolocationService

  MoveElevator\Typo3LoginWarning\Registry\DetectorRegistry:
    public: true
    arguments:
      $detectors: !tagged_iterator typo3_login_warning.detector

  MoveElevator\Typo3LoginWarning\Registry\NotificationRegistry:
    public: true
    arguments:
      $notifiers: !tagged_iterator typo3_login_warning.notifier

  MoveElevator\Typo3LoginWarning\Detector\NewIpDetector:
    public: true
    tags:
      - { name: typo3_login_warning.detector, priority: 100 }

  MoveElevator\Typo3LoginWarning\Detector\LongTimeNoSeeDetector:
    public: true
    tags:
      - { name: typo3_login_warning.detector, priority: 50 }

  MoveElevator\Typo3LoginWarning\Detector\OutOfOfficeDetector:
    public: true
    tags:
      - { name: typo3_login_warning.detector, priority: 10 }

  MoveElevator\Typo3LoginWarning\Notification\EmailNotification:
    tags:
      - { name: typo3_login_warning.notifier }

  # Login notification event listener
  MoveElevator\Typo3LoginWarning\Security\LoginNotification:
    tags:
      - name: event.listener
        identifier: 'move-elevator/typo3-login-warning/login-notification'
