name: Release
on:
  push:
    tags:
      - '*'

jobs:
  ter-publish:
    uses: jackd248/reusable-github-actions/.github/workflows/release-typo3.yml@main
    secrets:
      typo3-api-token: ${{ secrets.TYPO3_API_TOKEN }}
    with:
      typo3-extension-key: 'typo3_login_warning'
